INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Panasonic', 800, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Sony', 700, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Apple', 1000, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Sony Notebook', 1000, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Hewlett Packard', 500, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Bianchi', 600, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Nike', 100, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Adidas', 200, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATED_AT) VALUES('Reebok', 300, NOW());